before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: mx7alqVID0nVS9WqVQ/0HCJJTLSzKFUo7BfnkSN6e+xRHYo0RqYe8/h91ABd00dH+1Q1pspxHdGqf6GIx145pR5NsyHA3nXX2e4CT9RetUQ8Is8RJrfh4bfNZap2AvzNPWEEjltY1PEkfONQznIWrJ9fTrRcMvu+acony1wdBuCu9zaZmyCixrUCN/HwgWtYfXSp8o9MS4dDuGj0mY1lJAK+0QkhonJ8v3fTo943pGEi6uzEah5itv6B94TfivOo9dyfBy+dif/iYMA88djYginOV17YcFoFvEVzqoq353gl+XL5y3tY9TLnEnnCFrB1NnbBIFlHUcqvWpISoD2ozJ3AS5XVFpbph1gO8LKGhMWcynpHyswk6yMFpqBz9gdfDN1iHcPEzRYlq/7xnQQDdQXM2ClRufdSkSRkNU4S8eI/IL8TjAgEhGESGmKgOpZ6f7f0gkfpe2GwZ0fqlW78Pi8fVqSHfpVvhzJbDeSAt02mecpTxTi3oLiWgMp5zsOI49Ve978qqoTwLIeVPAXVwi2uBhwFkTTBYumtl/QXadZx+6VmgLyJ806VPaoslL3/UfQtL+jFaEFN9ixoPZYcjotU+I/c9OEA+u8ktUqCuQSvaBPHcqz0qRnjANxmImjC6TKXsNzxSbX54QrVG4mzrJbG3HfFqYiMnRQtzw8Z1YI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
